export const copy = {
  en: {
    title: "In Between",
    subtitle: "Mobile-first MVP for iframe-ready betting play",
    loginTitle: "Enter The Table",
    loginHint: "Use the seeded player account to test the live backend.",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing In...",
    quickAccess: "Quick Test Login",
    startSession: "Start Session",
    dealCards: "Deal Boundary Cards",
    settleBet: "Settle Bet",
    history: "Recent History",
    balance: "Balance",
    limits: "Bet Limits",
    table: "Table",
    logout: "Log Out",
    loading: "Loading table data...",
    idleTitle: "Ready To Deal",
    idleBody: "Start a session and reveal two boundary cards before you place a stake.",
    win: "Win",
    lose: "Lose",
    void: "Void",
    betAmount: "Bet Amount",
    roundStatus: "Round Status",
    result: "Result",
    openSessionFirst: "Start a session before dealing a round.",
  },
  zh: {
    title: "射龙门",
    subtitle: "可嵌入平台的移动端 MVP",
    loginTitle: "进入牌桌",
    loginHint: "可直接使用预设测试账号连接已启动的后端。",
    username: "用户名",
    password: "密码",
    signIn: "登录",
    signingIn: "登录中...",
    quickAccess: "快速测试登录",
    startSession: "开始牌局",
    dealCards: "派边牌",
    settleBet: "结算下注",
    history: "最近记录",
    balance: "余额",
    limits: "下注范围",
    table: "牌桌",
    logout: "退出",
    loading: "正在加载牌桌资料...",
    idleTitle: "准备开局",
    idleBody: "先开始一局，再发两张边牌后进行下注。",
    win: "赢",
    lose: "输",
    void: "无效",
    betAmount: "下注金额",
    roundStatus: "局状态",
    result: "结果",
    openSessionFirst: "请先开始一局再发牌。",
  },
} as const;

export type SupportedLocale = keyof typeof copy;
